### ISSUE TITLE
Add EGI branding to the theme

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/documentation#5]
Add EGI branding to the theme.

- @dscardaci suggested to remove the list of sections/subsections at the bottom of pages

**Comment by thebe14** [comment]
I think this was addressed by PR #244

**Comment by gwarf** [comment]
I think this was partially addressed, but the theme definitely need more work.
As an example https://docs.egi.eu/ or https://docs.egi.eu/users/ on the top left the logo is barely readable, things are not really aligned (and docs may also be better replaced by documentation).
We would also benefit from having some more EGI-specific look and feel (whatever it is...)

**Comment by gwarf** [comment]
Some previously collected feedback from communications team:
- Using a picture on the background (see "Communications"->"Photos and Image Database")
- Are you able to adapt it to our style guide, in terms of fonts and colours? (see colours in "Communications"->"EGI Logos")
- Is it possible to remove the 'shadow style' behind the headings?

**Comment by thebe14** [comment]
Is this now resolved?
Where is "Communications"->"Photos and Image Database"?

**Comment by gwarf** [comment]
I don't think the theme is really complete/clean enough.
The location mentioned relate the shared Google Drives. Seems it got moved under 01 Resources - Final.
It's also possible to clean this, and reconsider this task when the guidelines for EGI web sites/services will have been finalised/made available. Should happen in Q1 2023.
